version: '3'
services:
    nginx:
        image: nginx:latest
        # 端口映射
        ports:
            - "80:80"
        # 依赖关系 先跑php
        depends_on:
            - "php"
        # 数据卷
        volumes:
            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
            - "$PWD/nginx/conf.d:/etc/nginx/conf.d"
            - "$PWD/html:/var/www/html"
            - "/data/wwwroot/default:/data/wwwroot/default"
            - "$PWD/nginx/log:/var/log/nginx"
        networks:
            - app_net
        # 容器名称
        container_name: "compose-nginx"
    php:
        build: ./php
        # image指定build Dockerfile生成镜像的名称 #5.5.28-fpm
        image: php:5.5.28-fpm-mysqli
        ports:
            - "9000:9000"
        volumes:
            - "$PWD/html:/var/www/html"
            - "$PWD/php/conf:/usr/local/etc/php"
            - "/data/wwwroot/default:/data/wwwroot/default"
        networks:
            - app_net
        container_name: "compose-php"
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - "$PWD/mysql:/var/lib/mysql"
        # 环境变量
        environment:
            # mysql密码
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            app_net:
                # 固定子网ip，网段必须在子网络10.10.*.*
                ipv4_address: 10.10.10.1
        container_name: "compose-mysql"
networks:
    # 配置docker network
    app_net:
        driver: bridge
        ipam:
            config:
                # 子网络
                - subnet: 10.10.0.0/16
